server:
  port: 8901

#应用的名字
spring:
  application:
    name: ppl-server

#Redis配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 119.23.74.163  #Redis服务器地址
    port: 8003 # Redis服务器连接端口
    password: zzctest123456
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: 1000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接
        timeout: 0
    timeout:  100ms # 连接超时时间（毫秒）


