spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server


#      uri: http://localhost:8888/
server:
  port: 8882
debug: true
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8889/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
