eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7764
spring:
  application:
    name: service-lucy
management:
  endpoints:
    web:
      exposure:
        include:  hystrix.stream,actuator/hystrix,actuator,hystrix
debug: true