eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 3763
spring:
  application:
    name: service-hi
  zipkin:
    baseurl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include:  hystrix.stream