eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:9411
debug: true
feign:
  hystrix:
    enabled: true
    compression:
      request:
        enabled: true
      response:
        enabled: true